### ISSUE TITLE
subgraph issues (debug in flowhub)

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-browser-app#3]
http://forresto.github.io/the-graph-flux/main.html

Subgraph doesn't show ports:
![screen shot 2014-12-09 at 12 14 09 pm](https://cloud.githubusercontent.com/assets/395307/5361906/dce36276-7f9c-11e4-9eb9-51a984e2f7cd.png)

Opening subgraph fails with "runtime didn't provide source for graph in time."

**Comment by bergie** [comment]
@forresto I believe this is a Flowhub bug where we don't handle the command when dealing with live mode
