### ISSUE TITLE
How to run in flowhub IDE

### ISSUE THREAD

**Issue by shravantikatti** [noflo/noflo-browser-app#78]
How to depoly in flowhub IDE.
The link of github:
https://github.com/shravantikatti/Demo_Noflo_Data

We running in CLI its showing output. when wesave to github, unable to run.

What changes need to be done to run in flowhub IDE

**Comment by bergie** [comment]
That project doesn't appear to be a browser project? noflo-nodejs should show the URL needed to connect to Flowhub.
